//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pages
    {
        public int id { get; set; }
        public int document { get; set; }
        public int page { get; set; }
        public byte[] photo { get; set; }
    
        public virtual Documents Documents { get; set; }
    }
}
